module: KituraSMTP
author: IBM
github_url: https://github.com/IBM-Swift/Kitura-SMTP/

theme: fullwidth
clean: true
exclude: [Packages]

readme: README.md

skip_undocumented: false
hide_documentation_coverage: false

xcodebuild_arguments: [-project, KituraSMTP.xcodeproj, -target, KituraSMTP, LIBRARY_SEARCH_PATHS=.build/debug]