module: SwiftSMTP
author: IBM and Kitura project contributors
github_url: https://github.com/Kitura/Swift-SMTP/

theme: fullwidth
clean: true
exclude: [Packages]

readme: README.md

skip_undocumented: false
hide_documentation_coverage: false

xcodebuild_arguments: [-target, SwiftSMTP, LIBRARY_SEARCH_PATHS=.build/debug]
